[package]
name = "tmux-sysstat-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
bytesize = "2.4.2"
clap = { version = "4.6.1", features = ["derive"] }
psutil = "5.4.0"

[profile.release]
opt-level = 'z'
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 16
panic = 'abort'
incremental = false
overflow-checks = false
